#!/bin/sh

. $POSTMAN_PATH/httpUmbrella

prepareCatToken

# Define the request parameters
url="$APIM_HOST/api/myProject/scheduleservice/update"
headers="Application-id: $OWNER_WEB_APPLICATION_ID
auth-token: $access_token
Trace-Id: $TRACE_ID"
data_json=$(cat <<EOF
{
  "Vin": "$fpapp008_VIN",
  "frequency": "S"
}
EOF
)

execute_post_request \
--url="$url" \
--headers="$headers" \
--data-json "$data_json"