#!/bin/sh

set -e

pushd $Project_SCRIPT_PATH > /dev/null

. $Project_SCRIPT_PATH/color.sh
. $Project_SCRIPT_PATH/secretSupport

project_id=`grep projectID $Project_SCRIPT_PATH/projectInfo.txt | cut -d'=' -f2`

checkSecretInputs "$@"

if [[ ! -z $dataFileLocation ]]; then
  gcloud secrets create $secretKey --data-file=$dataFileLocation --project=${project_id} --replication-policy=user-managed --locations=us-central1,us-east4
elif [[ ! -z $secretValue ]]; then
  printf $secretValue | gcloud secrets create $secretKey --project=${project_id} --replication-policy=user-managed --locations=us-central1,us-east4 --data-file=-
else
  echo "should provide dataFileLocation or secretValue"
fi

echo "${GREEN} $secret created ${NO_COLOR}"

popd > /dev/null
