#!/usr/bin/env bash
echo

xcode-select --install && sleep 1
osascript -e 'tell application "System Events"' -e 'tell process "Install Command Line Developer Tools"' -e 'keystroke return' -e 'click button "Agree" of window "License Agreement"' -e 'end tell' -e 'end tell'

#brew install jq
#echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
