#!/bin/sh

set -e

pushd $Project_SCRIPT_PATH > /dev/null

. $Project_SCRIPT_PATH/color.sh
. $Project_SCRIPT_PATH/secretSupport

project_id=`grep projectID $Project_SCRIPT_PATH/projectInfo.txt | cut -d'=' -f2`

checkSecretInputs "$@"

if [[ ! -z $dataFileLocation ]]; then
  gcloud secrets versions add $secretKey --project=${project_id} --data-file=$dataFileLocation
elif [[ ! -z $secretValue ]]; then
  printf $secretValue | gcloud secrets versions add $secretKey --project="project_i" --data-file=-
else
  echo "should provide dataFileLocation or secretValue"
fi


# setting the --data-file=- flag to "-" will read the secret data from stdin.
#printf $secretValue | gcloud secrets create my-secret --data-file=-

echo "${GREEN} $secretKey updated with new version ${NO_COLOR}"

popd > /dev/null
