#!/bin/sh

if ! type execute_post_request > /dev/null 2>&1; then
  . $POSTMAN_PATH/httpUmbrella
fi

# Define the request parameters
url="$ADFS_HOST/adfs/oauth2/token"
headers="Content-Type: application/x-www-form-urlencoded"
data_urlencoded="client_id=$ADFS_CLIENT_ID
client_secret=$ADFS_CLIENT_SECRET
grant_type=client_credentials
scope=openid
resource=$1"

execute_post_request --url="$url" --headers="$headers" --data-urlencode="$data_urlencoded" --store-response